import Link from "next/link";
import { cookies } from "next/headers";
import { ArrowLeft, BrainCircuit, Save } from "lucide-react";
import { AgentActivityFeed } from "@/components/agent-activity-feed";
import { AiAgentCard } from "@/components/ai-agent-card";
import { addAgentActivity, addAgentRecommendation, saveAgentTask } from "@/app/actions/ai-agent-actions";
import { getAiAgentDashboard } from "@/lib/services/ai-agent-service";
import { signInOperator } from "../actions";

const OPERATOR_COOKIE = "myd1_operator_access";
const OPERATOR_COOKIE_VALUE = "granted";
const agentOptions = [{ value: "scout", label: "Scout Agent" }, { value: "recruiting", label: "Recruiting Agent" }, { value: "media", label: "Media Agent" }, { value: "training", label: "Training Agent" }, { value: "opportunity", label: "Opportunity Agent" }];

function UnlockPanel() { return <main className="min-h-screen bg-[#061331] px-6 py-10 text-white"><div className="mx-auto max-w-xl rounded-[34px] border border-white/10 bg-[#0A1A3F] p-6"><p className="text-xs font-black uppercase tracking-[0.24em] text-[#F2C200]">MyD1 Private Back Window</p><h1 className="mt-3 text-4xl font-black">Unlock Agent Command</h1><form action={signInOperator} className="mt-6 grid gap-3"><input className="min-h-12 rounded-2xl bg-white px-4 text-sm font-black text-[#061331] outline-none" name="accessCode" placeholder="Operator access code" type="password" /><button className="min-h-12 rounded-2xl bg-[#F2C200] px-5 text-sm font-black text-[#061331]" type="submit">Unlock</button></form></div></main>; }
function AgentSelect() { return <select name="agentKey" className="min-h-12 rounded-2xl bg-white px-4 text-sm font-black text-[#061331]">{agentOptions.map((agent) => <option key={agent.value} value={agent.value}>{agent.label}</option>)}</select>; }

export default async function OperationsAgentActivityPage({ searchParams }: { searchParams?: Promise<{ status?: string }> }) {
  const params = searchParams ? await searchParams : {};
  const cookieStore = await cookies();
  const isOperator = cookieStore.get(OPERATOR_COOKIE)?.value === OPERATOR_COOKIE_VALUE;
  if (!isOperator) return <UnlockPanel />;
  const dashboard = getAiAgentDashboard();
  return <main className="min-h-screen bg-[#061331] px-4 py-6 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1700px]"><header className="rounded-[30px] border border-white/10 bg-[#0A1A3F] p-5"><Link href="/operations" className="inline-flex items-center gap-2 text-sm font-black text-[#CAD7FF]"><ArrowLeft size={16} /> Back to Platform Management</Link><div className="mt-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.24em] text-[#F2C200]">AI Agent System</p><h1 className="mt-2 text-4xl font-black">Agent Command Center</h1><p className="mt-2 max-w-3xl text-sm font-semibold leading-6 text-[#CAD7FF]">Manage specialized agents and review the live activity stream before actions move through the platform.</p></div><Link href="/ai-team" className="rounded-2xl bg-[#F2C200] px-5 py-3 text-sm font-black text-[#061331]">Open My AI Team</Link></div>{params.status ? <div className="mt-4 rounded-2xl border border-[#8CFF00]/30 bg-[#8CFF00]/10 px-4 py-3 text-sm font-black text-[#8CFF00]">Agent command saved.</div> : null}</header>
  <section className="mt-5 grid gap-4 md:grid-cols-5"><div className="rounded-[24px] border border-white/10 bg-white/[0.07] p-5"><p className="text-xs font-black uppercase text-[#CAD7FF]">Agents</p><p className="mt-2 text-4xl font-black text-white">{dashboard.totals.agents}</p></div><div className="rounded-[24px] border border-white/10 bg-white/[0.07] p-5"><p className="text-xs font-black uppercase text-[#CAD7FF]">Active</p><p className="mt-2 text-4xl font-black text-[#8CFF00]">{dashboard.totals.active}</p></div><div className="rounded-[24px] border border-white/10 bg-white/[0.07] p-5"><p className="text-xs font-black uppercase text-[#CAD7FF]">Review</p><p className="mt-2 text-4xl font-black text-[#F2C200]">{dashboard.totals.review}</p></div><div className="rounded-[24px] border border-white/10 bg-white/[0.07] p-5"><p className="text-xs font-black uppercase text-[#CAD7FF]">Recommendations</p><p className="mt-2 text-4xl font-black text-white">{dashboard.totals.recommendations}</p></div><div className="rounded-[24px] border border-white/10 bg-white/[0.07] p-5"><p className="text-xs font-black uppercase text-[#CAD7FF]">Activity</p><p className="mt-2 text-4xl font-black text-[#8CFF00]">{dashboard.totals.activity}</p></div></section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[430px_1fr]"><div className="grid gap-5"><form action={addAgentActivity} className="rounded-[30px] border border-white/12 bg-[#071A43] p-5"><div className="flex items-center gap-3"><BrainCircuit className="text-[#F2C200]" /><h2 className="text-2xl font-black">Add activity</h2></div><div className="mt-5 grid gap-4"><label className="grid gap-2 text-sm font-black"><span>Agent</span><AgentSelect /></label><label className="grid gap-2 text-sm font-black"><span>Activity type</span><select name="type" className="min-h-12 rounded-2xl bg-white px-4 text-sm font-black text-[#061331]"><option value="found">Found</option><option value="generated">Generated</option><option value="matched">Matched</option><option value="updated">Updated</option><option value="recommended">Recommended</option><option value="queued">Queued</option></select></label><label className="grid gap-2 text-sm font-black"><span>Message</span><input name="message" placeholder="Scout Agent found two tournaments." className="min-h-12 rounded-2xl bg-white px-4 text-sm font-semibold text-[#061331]" /></label><label className="grid gap-2 text-sm font-black"><span>Target</span><input name="target" placeholder="Tournament leads" className="min-h-12 rounded-2xl bg-white px-4 text-sm font-semibold text-[#061331]" /></label><button className="min-h-12 rounded-2xl bg-[#F2C200] px-5 text-sm font-black uppercase text-[#061331]" type="submit"><Save className="inline" size={16} /> Add activity</button></div></form>
  <form action={saveAgentTask} className="rounded-[30px] border border-white/12 bg-[#071A43] p-5"><h2 className="text-2xl font-black">Update agent card</h2><div className="mt-5 grid gap-4"><label className="grid gap-2 text-sm font-black"><span>Agent</span><AgentSelect /></label><label className="grid gap-2 text-sm font-black"><span>Status</span><select name="status" className="min-h-12 rounded-2xl bg-white px-4 text-sm font-black text-[#061331]"><option value="active">Active</option><option value="waiting">Waiting</option><option value="review">Review</option><option value="paused">Paused</option></select></label><label className="grid gap-2 text-sm font-black"><span>Current task</span><textarea name="currentTask" className="min-h-20 rounded-2xl bg-white px-4 py-3 text-sm font-semibold text-[#061331]" /></label><label className="grid gap-2 text-sm font-black"><span>Last completed task</span><textarea name="lastCompletedTask" className="min-h-20 rounded-2xl bg-white px-4 py-3 text-sm font-semibold text-[#061331]" /></label><label className="grid gap-2 text-sm font-black"><span>Next recommendation</span><textarea name="nextRecommendation" className="min-h-20 rounded-2xl bg-white px-4 py-3 text-sm font-semibold text-[#061331]" /></label><button className="min-h-12 rounded-2xl bg-[#8CFF00] px-5 text-sm font-black uppercase text-[#061331]" type="submit">Save agent</button></div></form>
  <form action={addAgentRecommendation} className="rounded-[30px] border border-white/12 bg-[#071A43] p-5"><h2 className="text-2xl font-black">Add recommendation</h2><div className="mt-5 grid gap-4"><label className="grid gap-2 text-sm font-black"><span>Agent</span><AgentSelect /></label><label className="grid gap-2 text-sm font-black"><span>Priority</span><select name="priority" className="min-h-12 rounded-2xl bg-white px-4 text-sm font-black text-[#061331]"><option value="medium">Medium</option><option value="high">High</option><option value="low">Low</option></select></label><label className="grid gap-2 text-sm font-black"><span>Title</span><input name="title" className="min-h-12 rounded-2xl bg-white px-4 text-sm font-semibold text-[#061331]" /></label><label className="grid gap-2 text-sm font-black"><span>Recommendation</span><textarea name="recommendation" className="min-h-24 rounded-2xl bg-white px-4 py-3 text-sm font-semibold text-[#061331]" /></label><button className="min-h-12 rounded-2xl bg-[#F2C200] px-5 text-sm font-black uppercase text-[#061331]" type="submit">Add recommendation</button></div></form></div>
  <div className="grid gap-5"><AgentActivityFeed activity={dashboard.activity} /><section className="grid gap-4 xl:grid-cols-2">{dashboard.agents.map((agent) => <AiAgentCard key={agent.key} agent={agent} />)}</section></div></section></div></main>;
}
