import Link from "next/link";
import { cookies } from "next/headers";
import { ArrowLeft, Radio, UploadCloud } from "lucide-react";
import { MediaConnectionCard } from "@/components/media-connection-card";
import { MediaSyncStatus } from "@/components/media-sync-status";
import { queueMediaImport, reviewMediaItem } from "@/app/actions/media-connection-actions";
import { getConnectedMediaDashboard } from "@/lib/services/media-agent-service";
import { signInOperator } from "../actions";

const OPERATOR_COOKIE = "myd1_operator_access";
const OPERATOR_COOKIE_VALUE = "granted";

function UnlockPanel() {
  return <main className="min-h-screen bg-[#061331] px-6 py-10 text-white"><div className="mx-auto max-w-xl rounded-[34px] border border-white/10 bg-[#0A1A3F] p-6"><p className="text-xs font-black uppercase tracking-[0.24em] text-[#F2C200]">MyD1 Private Back Window</p><h1 className="mt-3 text-4xl font-black">Unlock Media Operations</h1><form action={signInOperator} className="mt-6 grid gap-3"><input className="min-h-12 rounded-2xl bg-white px-4 text-sm font-black text-[#061331] outline-none" name="accessCode" placeholder="Operator access code" type="password" /><button className="min-h-12 rounded-2xl bg-[#F2C200] px-5 text-sm font-black text-[#061331]" type="submit">Unlock</button></form></div></main>;
}

export default async function OperationsMediaConnectionsPage({ searchParams }: { searchParams?: Promise<{ status?: string }> }) {
  const params = searchParams ? await searchParams : {};
  const cookieStore = await cookies();
  const isOperator = cookieStore.get(OPERATOR_COOKIE)?.value === OPERATOR_COOKIE_VALUE;
  if (!isOperator) return <UnlockPanel />;
  const dashboard = getConnectedMediaDashboard();
  return <main className="min-h-screen bg-[#061331] px-4 py-6 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1600px]"><header className="rounded-[30px] border border-white/10 bg-[#0A1A3F] p-5"><Link href="/operations" className="inline-flex items-center gap-2 text-sm font-black text-[#CAD7FF]"><ArrowLeft size={16} /> Back to Platform Management</Link><div className="mt-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.24em] text-[#F2C200]">Connected Media Engine</p><h1 className="mt-2 text-4xl font-black">Media Operations</h1><p className="mt-2 max-w-3xl text-sm font-semibold leading-6 text-[#CAD7FF]">Review connected media, manual imports, and publishing decisions before anything is used publicly.</p></div><Link href="/media-connections" className="rounded-2xl bg-[#F2C200] px-5 py-3 text-sm font-black text-[#061331]">Open athlete media page</Link></div>{params.status ? <div className="mt-4 rounded-2xl border border-[#8CFF00]/30 bg-[#8CFF00]/10 px-4 py-3 text-sm font-black text-[#8CFF00]">Media operation saved.</div> : null}</header>
  <section className="mt-5 grid gap-4 md:grid-cols-4"><div className="rounded-[24px] border border-white/10 bg-white/[0.07] p-5"><p className="text-xs font-black uppercase text-[#CAD7FF]">Connected</p><p className="mt-2 text-4xl font-black text-[#8CFF00]">{dashboard.totals.connected}</p></div><div className="rounded-[24px] border border-white/10 bg-white/[0.07] p-5"><p className="text-xs font-black uppercase text-[#CAD7FF]">Imports</p><p className="mt-2 text-4xl font-black text-[#F2C200]">{dashboard.totals.imported}</p></div><div className="rounded-[24px] border border-white/10 bg-white/[0.07] p-5"><p className="text-xs font-black uppercase text-[#CAD7FF]">Pending</p><p className="mt-2 text-4xl font-black text-white">{dashboard.totals.pendingReview}</p></div><div className="rounded-[24px] border border-white/10 bg-white/[0.07] p-5"><p className="text-xs font-black uppercase text-[#CAD7FF]">Approved</p><p className="mt-2 text-4xl font-black text-[#8CFF00]">{dashboard.totals.approved}</p></div></section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[420px_1fr]"><form action={queueMediaImport} className="rounded-[30px] border border-white/12 bg-[#071A43] p-5"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#F2C200] text-[#061331]"><UploadCloud /></span><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#F2C200]">Manual import</p><h2 className="text-2xl font-black">Queue media for review</h2></div></div><div className="mt-5 grid gap-4"><label className="grid gap-2 text-sm font-black"><span>Platform</span><select name="platform" className="min-h-12 rounded-2xl bg-white px-4 text-sm font-black text-[#061331]"><option value="instagram">Instagram</option><option value="tiktok">TikTok</option><option value="youtube">YouTube</option><option value="x">X</option><option value="facebook">Facebook</option></select></label><label className="grid gap-2 text-sm font-black"><span>Athlete name</span><input name="athleteName" placeholder="Current Athlete" className="min-h-12 rounded-2xl bg-white px-4 text-sm font-black text-[#061331]" /></label><label className="grid gap-2 text-sm font-black"><span>Source URL</span><input name="sourceUrl" placeholder="https://..." className="min-h-12 rounded-2xl bg-white px-4 text-sm font-semibold text-[#061331]" /></label><label className="grid gap-2 text-sm font-black"><span>Title</span><input name="title" placeholder="Highlight title" className="min-h-12 rounded-2xl bg-white px-4 text-sm font-black text-[#061331]" /></label><label className="grid gap-2 text-sm font-black"><span>Caption / notes</span><textarea name="caption" className="min-h-24 rounded-2xl bg-white px-4 py-3 text-sm font-semibold text-[#061331]" /></label><button className="min-h-12 rounded-2xl bg-[#F2C200] px-5 text-sm font-black uppercase text-[#061331]" type="submit">Queue review</button></div></form>
  <div className="grid gap-5"><section className="rounded-[30px] border border-white/12 bg-white/[0.06] p-5"><div className="flex items-center gap-3"><Radio className="text-[#8CFF00]" /><h2 className="text-2xl font-black">Connected accounts</h2></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{dashboard.connections.length ? dashboard.connections.map((connection) => <MediaConnectionCard key={connection.id} connection={connection} mode="operations" />) : <div className="rounded-2xl border border-dashed border-white/20 p-6 text-sm font-semibold text-[#CAD7FF]">No connected accounts yet.</div>}</div></section>
  <section className="rounded-[30px] border border-white/12 bg-white/[0.06] p-5"><h2 className="text-2xl font-black">Review queue</h2><div className="mt-5 grid gap-3">{dashboard.reviewQueue.length ? dashboard.reviewQueue.map((item) => <div key={item.id} className="rounded-2xl border border-white/10 bg-[#071A43] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#F2C200]">{item.platform} · {item.athleteName}</p><h3 className="mt-1 text-xl font-black">{item.title}</h3><a href={item.sourceUrl} className="mt-2 block truncate text-xs font-semibold text-[#CAD7FF]">{item.sourceUrl}</a></div><MediaSyncStatus status={item.status} /></div>{item.status === "pending" ? <form action={reviewMediaItem} className="mt-4 grid gap-3 md:grid-cols-[1fr_auto_auto]"><input type="hidden" name="reviewId" value={item.id} /><input name="notes" placeholder="Review notes" className="min-h-11 rounded-2xl bg-white px-4 text-sm font-semibold text-[#061331]" /><button name="reviewAction" value="approve" className="rounded-2xl bg-[#8CFF00] px-5 text-sm font-black uppercase text-[#061331]" type="submit">Approve</button><button name="reviewAction" value="reject" className="rounded-2xl border border-white/10 bg-white/[0.08] px-5 text-sm font-black uppercase text-white" type="submit">Reject</button></form> : null}</div>) : <div className="rounded-2xl border border-dashed border-white/20 p-6 text-sm font-semibold text-[#CAD7FF]">No media in review yet.</div>}</div></section></div></section></div></main>;
}
